export const USE_GROUPS_QUERY_KEY = 'USE_GROUPS';
export const USE_GROUP_QUERY_KEY = 'USE_GROUP';
export const USE_SELECTED_GROUP_QUERY_KEY = 'USE_SELECTED_GROUP';

export const CREATE_GROUP_MUTATION_KEY = 'CREATE_GROUP';
export const UPDATE_GROUP_MUTATION_KEY = 'UPDATE_GROUP';
export const DELETE_GROUP_MUTATION_KEY = 'DELETE_GROUP';
