export const USE_GROUP_INVITES_QUERY_KEY = 'GROUP_INVITES';
export const USE_INVITED_USERS_QUERY_KEY = 'USER_INVITES';

export const MANAGE_GROUP_INVITE_MUTATION_KEY = 'MANAGE_GROUP_INVITE';
export const SEND_GROUP_INVITE_MUTATION_KEY = 'SEND_GROUP_INVITE';
export const DELETE_GROUP_INVITE_MUTATION_KEY = 'DELETE_GROUP_INVITE';
